/*
 * This source file was generated by the Gradle 'init' task
 */
package edu.curso;

public class Aluno {
        private long id;
        private String ra;
        private String nome;
        private LocalDate nascimento;
}

public Aluno(long id, String ra, String nome, LocalDate nascimento) {
    
    this.id = id;
    this.ra = ra;
    this.nome =ra;
    this.nascimento = nascimento;

}

public Aluno(){

}


   

